name: "aws deploy composite step."
description: "deploy website to ec2 and assets to s3."
inputs:
  AWS_ACCESS_KEY_ID:
    description: "aws-cli requirement."
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "aws-cli requirement."
    required: true
  TARGET:
    description: "target directory, to be published."
    required: true
  S3_ASSETS_PATH:
    description: "Full s3 bucket path eg. s3://s3-bucket-name/sub/path"
    required: true
  EC2_ADDRESS:
    description: "ssh address eg. 'username@host'."
    required: true
  EC2_DEPLOY_PATH:
    description: "absolute path on remote machine, to deploy."
    required: true
runs:
  using: "composite"
  steps:
    - name: Deploy static assets to S3 bucket.
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        S3_ASSETS_PATH: ${{ inputs.S3_ASSETS_PATH }}
        TARGET: ${{ inputs.TARGET }}
      run: |
        aws s3 sync $TARGET $S3_ASSETS_PATH \
        --exclude "*.html" --exclude "*.webmanifest" \
        --exclude ".git*" --exclude "README*" --exclude "p/*" \
        --delete --acl public-read

    - name: Deploy site to EC2.
      shell: bash
      env:
        TARGET: ${{ inputs.TARGET }}
        ADDRESS: ${{ inputs.EC2_ADDRESS }}
        PATH: ${{ inputs.EC2_DEPLOY_PATH }}
      run: |
        rsync -avP --delete-excluded \
        --include="*.html" --include="*.webmanifest" \
        --exclude=".git*" --exclude="p" --include="*/" --exclude="*" \
        --rsync-path="mkdir -p $PATH && rsync" \
        -e "ssh -o StrictHostKeyChecking=no" $TARGET/. $ADDRESS:$PATH
        echo "getting rid of empty directories generated by rsync."
        ssh $ADDRESS "find $PATH -type d -empty -delete"
