name: "aws deploy composite step."
description: "My personal deploy action (ec2 and s3)."
author: 'LycuiD <lycuid@gmail.com>'
inputs:
  TARGET:
    description: "target directory, to be published."
    required: true
  GPG_KEY:
    description: "GPG key to decrypt secret env variables."
    required: true
  GPG_PASSPHRASE:
    description: "GPG Passphrase for the key."
    required: true
  EC2_REMOTE_PATH:
    description: "absolute path on remote machine (where to deploy)."
    required: true
  S3_BUCKET_PATH:
    description: "Full s3 bucket path eg. s3://s3-bucket-name/sub/path"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
