#!/usr/bin/env bash
set -e

TARGET="$INPUT_TARGET"
GPG_KEY="$INPUT_GPG_KEY"
GPG_PASSPHRASE="$INPUT_GPG_PASSPHRASE"
EC2_REMOTE_PATH="$INPUT_EC2_REMOTE_PATH"
S3_BUCKET_PATH="$INPUT_S3_BUCKET_PATH"

GPG_FLAGS=(--pinentry-mode loopback --passphrase "$GPG_PASSPHRASE")

echo "========== Importing gpg key. =========="
echo "$GPG_KEY" | gpg ${GPG_FLAGS[@]} --import

echo "========== Decrypting and exporting secret env variables. =========="
export $(gpg ${GPG_FLAGS[@]} --decrypt /secrets/ENCRYPTED_ENV_VARS 2>/dev/null | xargs)

echo "========== Decrypting aws ec2 ssh key. =========="
EC2_SSH_KEY=$(gpg ${GPG_FLAGS[@]} --decrypt /secrets/ENCRYPTED_EC2_SSH_KEY 2>/dev/null)

# Installing aws cli for deploying to s3.
pip3 install awscli

## Setting up ssh.
eval "$(ssh-agent)"
echo "$EC2_SSH_KEY" | ssh-add -

## Deployment.
echo "========== Deploying assets to S3. =========="
aws s3 sync $TARGET $S3_BUCKET_PATH \
  --exclude "*.html" --exclude "*.webmanifest" --exclude "p/*" \
  --delete --acl public-read

echo "========== Deploying to EC2. =========="
rsync -avP --delete-excluded \
  --include="*.html" --include="*.webmanifest" \
  --exclude="p" --include="*/" --exclude="*" \
  --rsync-path="mkdir -p $EC2_REMOTE_PATH && rsync" \
  -e "ssh -o StrictHostKeyChecking=no" $TARGET/. $EC2_REMOTE_ADDR:$EC2_REMOTE_PATH

echo "========== getting rid of empty directories generated by rsync. =========="
ssh $EC2_REMOTE_ADDR "find $EC2_REMOTE_PATH -type d -empty -delete"
